openapi: '3.0.3'
info:
  title: API 
  version: '1.0.1'
tags:
  - name: ragAgents
    description: RAG-агенты
  - name: docs
    description: Документы
  - name: llm
    description: Языковые модели
servers:
  - url: http://ai.artcheroff.ru/api/v1/
paths:
  /docs:
    get:
      tags:
        - docs
      summary: Получить набор документов
      description: Метод возвращается список документов пользователя
      parameters:
        - name: dateUpload
          in: query
          description: Дата загрузки документа
          schema:
            type: string
            format: date-time
        - name: status
          in: query
          description: Статус документа
          schema:
            type: string
            enum: [created, saved, embedded]
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/doc'
        '401':
          description: Недостаточно прав
    post:
      tags:
        - docs
      summary: Загрузить документ
      description: Метод возвращает статус получения документа
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                    type: string
                    example: "Документ.pdf"
                content:
                    type: string
                    example: "JVBERi0xLjQKJSA0IDAgb2JqCjw8L0ZpbHRlci9GbFlQ..."
                dateUpload:
                    type: string
                    format: date-time
      responses:
        '200':
          description: Успешно
    put:
      tags:
        - docs
      summary: Заменить документ
      description: Метод возвращает статус замены документа
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  id:
                    type: string
                    format: uuid
                    example: 550e8400-e29b-41d4-a716-446655440000                    
                  name:
                      type: string
                      example: "Документ.pdf"
                  content:
                      type: string
                      format: binary
                      example: "JVBERi0xLjQKJSA0IDAgb2JqCjw8L0ZpbHRlci9GbFlQ..."
                  dateUpload:
                      type: string
                      format: date-time           
      responses:
        '200':
          description: Успешно
  /ragModels:
    get:
      tags: 
        - ragAgents
      summary: Получить RAG-агента
      description: Метод возвращает список RAG-моделей пользователя
      parameters:
        - name: dateBegin
          in: query
          description: Дата создания RAG-агента
          schema:
            type: string
            format: date-time
        - name: status
          in: query
          description: Статус RAG-агента
          schema:
            type: string
            enum: [active, deleted]
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/ragAgent'
components:
  schemas:
    ragAgent:
      description: Объект RAG-агента
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор RAG-агента
          example: 550e8400-e29b-41d4-a716-446655440000
        desc:
          type: string
          description: Описание RAG-агента
          default: null
          example: Эксперт по фитнесу
    doc:
      type: object
      description: Объект документа
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор документа
          example: 550e8400-e29b-41d4-a716-446655440000
        name:
          type: string
          description: Название документа
          example: 'Документ.pdf'
        content:
          type: string
          description: Содержимое документа
          example: JVBERi0xLjQKJSA0IDAgb2JqCjw8L0ZpbHRlci9GbFlQ...
        dateUpload:
          type: string
          format: date-time
          example: 2025-01-01T19:10:00
          description: Дата загрузки документа
        size:
          type: string
          description: Объем документа в Мб
          example: 100 MB
        status:
          type: string
          enum: [uploaded, saved, embedded]
          description: Статус обработки документа
    